load("//:annop.bzl", "tf_kernel_library")

tf_kernel_library(
    name = "zero_out_op",
    srcs = [
        "ZeroOutOp.cc",
    ],
    hdrs = ["ZeroOutOp.h"],
    deps = [
        "@tensorflow//:tensorflow_framework"
    ]
)